### ISSUE TITLE
Version 4.5.5.62 fails to install on Raspberry Pi

### ISSUE THREAD

**Issue by pauljurczak** [opencv/opencv-python#612]
My configuration:
```
pi@raspberrypi:~ $ neofetch
  `.::///+:/-.        --///+//-:``    pi@raspberrypi 
 `+oooooooooooo:   `+oooooooooooo:    -------------- 
  /oooo++//ooooo:  ooooo+//+ooooo.    OS: Raspbian GNU/Linux 10 (buster) armv7l 
  `+ooooooo:-:oo-  +o+::/ooooooo:     Host: Raspberry Pi 4 Model B Rev 1.4 
   `:oooooooo+``    `.oooooooo+-      Kernel: 5.10.63-v7l+ 
     `:++ooo/.        :+ooo+/.`       Uptime: 34 days, 6 hours, 8 mins 
        ...`  `.----.` ``..           Packages: 2328 (dpkg) 
     .::::-``:::::::::.`-:::-`        Shell: bash 5.0.3 
    -:::-`   .:::::::-`  `-:::-       Terminal: /dev/pts/1 
   `::.  `.--.`  `` `.---.``.::`      CPU: BCM2711 (4) @ 1.500GHz 
       .::::::::`  -::::::::` `       Memory: 345MiB / 7719MiB 
pi@raspberrypi:~ $ python3 --version
Python 3.7.3
pi@raspberrypi:~ $ pip --version
pip 21.3.1 from /home/pi/.local/lib/python3.7/site-packages/pip (python 3.7)
```
I have an older version, which works just fine:
```
opencv-contrib-python 4.5.3.56
```
Installation fails with these messages:
```
pi@raspberrypi:~/pick $ pip install --upgrade opencv-contrib-python
Defaulting to user installation because normal site-packages is not writeable
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Requirement already satisfied: opencv-contrib-python in /home/pi/.local/lib/python3.7/site-packages (4.5.3.56)
Collecting opencv-contrib-python
  Using cached opencv-contrib-python-4.5.5.62.tar.gz (150.4 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: numpy>=1.14.5 in /home/pi/.local/lib/python3.7/site-packages (from opencv-contrib-python) (1.21.4)
Building wheels for collected packages: opencv-contrib-python
  Building wheel for opencv-contrib-python (pyproject.toml) ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python3 /home/pi/.local/lib/python3.7/site-packages/pip/_vendor/pep517/in_process/_in_process.py build_wheel /tmp/tmp0pwnyagk
       cwd: /tmp/pip-install-b4yo4rie/opencv-contrib-python_23756fb2c01b4849b12d8da4f7866dcf
  Complete output (5119 lines):
  patching file opencv/3rdparty/openexr/IlmImf/ImfSystemSpecific.cpp
  Not searching for unused variables given on the command line.
  CMake Error at CMakeLists.txt:2 (PROJECT):
    Running
  
     '/usr/sbin/ninja' '--version'
  
    failed with:
  
     die: error: must run as root
```

**Comment by pauljurczak** [comment]
`opencv-contrib-python-4.5.4.60` installs successfully, too.

**Comment by alalek** [comment]
> /usr/sbin/ninja

What is that on used system?
Why is it in "sbin"?

**Comment by pauljurczak** [comment]
I installed Ninja with `sudo apt install ninja-build`, since the previous attempt of installing `opencv-contrib-python` failed with numerous error messages indicating that Ninja was needed, but not found. I don't know why `apt` put it in `/usr/sbin`.

**Comment by pauljurczak** [comment]
I installed Ninja with `sudo apt install ninja-build`, since the previous attempt of installing `opencv-contrib-python` failed with numerous error messages indicating that Ninja was needed, but not found. I don't know why `apt` put it in `/usr/sbin`. It does require root to run:
```
pi@raspberrypi:/usr/sbin $ ninja --version
log: ninja version 0.1.3 initializing
die: error: must run as root
```

**Comment by alalek** [comment]
> You want want /usr/bin/ninja (apt install ninja-build, https://ninja-build.org/), not /usr/sbin/ninja (apt install ninja), a similarly named but unrelated tool.

Ref: From Internet.

---

- Clean CMake cache and start from scratch.
- Check PATH settings.
- Remove invalid package

**Comment by pauljurczak** [comment]
Accidentally, both `ninja` and `ninja-build` were installed. I removed `ninja`, but there are C++ compilation errors now, e.g.:
```
  /usr/include/python3.7m/numpy/ndarrayobject.h:236:9: error: ‘PyTuple_GET_SIZE’ was not declared in this scope
       if (PyTuple_GET_SIZE(value) != 3) {
```

<details>
<summary>Build log</summary>

```

```
pi@raspberrypi:~ $ pip install --upgrade opencv-contrib-python
Defaulting to user installation because normal site-packages is not writeable
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Requirement already satisfied: opencv-contrib-python in ./.local/lib/python3.7/site-packages (4.5.4.60)
Collecting opencv-contrib-python
  Using cached opencv-contrib-python-4.5.5.62.tar.gz (150.4 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: numpy>=1.14.5 in ./.local/lib/python3.7/site-packages (from opencv-contrib-python) (1.21.4)
Building wheels for collected packages: opencv-contrib-python
  Building wheel for opencv-contrib-python (pyproject.toml) ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python3 /home/pi/.local/lib/python3.7/site-packages/pip/_vendor/pep517/in_process/_in_process.py build_wheel /tmp/tmpo704h92w
       cwd: /tmp/pip-install-lvel8qyn/opencv-contrib-python_eafbac0653b8480faaa76d62d11bdf93
  Complete output (5081 lines):
  patching file opencv/3rdparty/openexr/IlmImf/ImfSystemSpecific.cpp
  Not searching for unused variables given on the command line.
  -- The C compiler identification is GNU 8.3.0
  -- Detecting C compiler ABI info
  -- Detecting C compiler ABI info - done
  -- Check for working C compiler: /usr/bin/cc - skipped
  -- Detecting C compile features
  -- Detecting C compile features - done
  -- The CXX compiler identification is GNU 8.3.0
  -- Detecting CXX compiler ABI info
  -- Detecting CXX compiler ABI info - done
  -- Check for working CXX compiler: /usr/bin/c++ - skipped
  -- Detecting CXX compile features
  -- Detecting CXX compile features - done
  -- Configuring done
  -- Generating done
  -- Build files have been written to: /tmp/pip-install-lvel8qyn/opencv-contrib-python_eafbac0653b8480faaa76d62d11bdf93/_cmake_test_compile/build
  -- The CXX compiler identification is GNU 8.3.0
  -- The C compiler identification is GNU 8.3.0
  -- Detecting CXX compiler ABI info
  -- Detecting CXX compiler ABI info - done
  -- Check for working CXX compiler: /usr/bin/c++ - skipped
  -- Detecting CXX compile features
  -- Detecting CXX compile features - done
  -- Detecting C compiler ABI info
  -- Detecting C compiler ABI info - done
  -- Check for working C compiler: /usr/bin/cc - skipped
  -- Detecting C compile features
  -- Detecting C compile features - done
  -- Detected processor: armv7l
  -- Found PythonInterp: /usr/bin/python3 (found suitable version "3.7.3", minimum required is "2.7")
  CMake Warning at cmake/OpenCVDetectPython.cmake:81 (message):
    CMake's 'find_host_package(PythonInterp 2.7)' found wrong Python version:
  
    PYTHON_EXECUTABLE=/usr/bin/python3
  
    PYTHON_VERSION_STRING=3.7.3
  
    Consider providing the 'PYTHON2_EXECUTABLE' variable via CMake command line
    or environment variables
  
  Call Stack (most recent call first):
    cmake/OpenCVDetectPython.cmake:271 (find_python)
    CMakeLists.txt:627 (include)
  
  
  -- Could NOT find Python2 (missing: Interpreter)
      Reason given by package:
          Interpreter: Cannot run the interpreter "/usr/bin/python2"
  
  -- Found PythonInterp: /usr/bin/python2
  -- Found PythonInterp: /usr/bin/python3 (found suitable version "3.7.3", minimum required is "3.2")
  -- Found PythonLibs: /usr/lib/arm-linux-gnueabihf/libpython3.7m.so (found suitable exact version "3.7.3")
  -- Looking for ccache - not found
  -- Performing Test HAVE_CXX_FSIGNED_CHAR
  -- Performing Test HAVE_CXX_FSIGNED_CHAR - Success
  -- Performing Test HAVE_C_FSIGNED_CHAR
  -- Performing Test HAVE_C_FSIGNED_CHAR - Success
  -- Performing Test HAVE_CXX_W
  -- Performing Test HAVE_CXX_W - Success
  -- Performing Test HAVE_C_W
  -- Performing Test HAVE_C_W - Success
  -- Performing Test HAVE_CXX_WALL
  -- Performing Test HAVE_CXX_WALL - Success
  -- Performing Test HAVE_C_WALL
  -- Performing Test HAVE_C_WALL - Success
  -- Performing Test HAVE_CXX_WERROR_RETURN_TYPE
  -- Performing Test HAVE_CXX_WERROR_RETURN_TYPE - Success
  -- Performing Test HAVE_C_WERROR_RETURN_TYPE
  -- Performing Test HAVE_C_WERROR_RETURN_TYPE - Success
  -- Performing Test HAVE_CXX_WERROR_NON_VIRTUAL_DTOR
  -- Performing Test HAVE_CXX_WERROR_NON_VIRTUAL_DTOR - Success
  -- Performing Test HAVE_C_WERROR_NON_VIRTUAL_DTOR
  -- Performing Test HAVE_C_WERROR_NON_VIRTUAL_DTOR - Success
  -- Performing Test HAVE_CXX_WERROR_ADDRESS
  -- Performing Test HAVE_CXX_WERROR_ADDRESS - Success
  -- Performing Test HAVE_C_WERROR_ADDRESS
  -- Performing Test HAVE_C_WERROR_ADDRESS - Success
  -- Performing Test HAVE_CXX_WERROR_SEQUENCE_POINT
  -- Performing Test HAVE_CXX_WERROR_SEQUENCE_POINT - Success
  -- Performing Test HAVE_C_WERROR_SEQUENCE_POINT
  -- Performing Test HAVE_C_WERROR_SEQUENCE_POINT - Success
  -- Performing Test HAVE_CXX_WFORMAT
  -- Performing Test HAVE_CXX_WFORMAT - Success
  -- Performing Test HAVE_C_WFORMAT
  -- Performing Test HAVE_C_WFORMAT - Success
  -- Performing Test HAVE_CXX_WERROR_FORMAT_SECURITY
  -- Performing Test HAVE_CXX_WERROR_FORMAT_SECURITY - Success
  -- Performing Test HAVE_C_WERROR_FORMAT_SECURITY
  -- Performing Test HAVE_C_WERROR_FORMAT_SECURITY - Success
  -- Performing Test HAVE_CXX_WMISSING_DECLARATIONS
  -- Performing Test HAVE_CXX_WMISSING_DECLARATIONS - Success
  -- Performing Test HAVE_C_WMISSING_DECLARATIONS
  -- Performing Test HAVE_C_WMISSING_DECLARATIONS - Success
  -- Performing Test HAVE_CXX_WMISSING_PROTOTYPES
  -- Performing Test HAVE_CXX_WMISSING_PROTOTYPES - Failed
  -- Performing Test HAVE_C_WMISSING_PROTOTYPES
  -- Performing Test HAVE_C_WMISSING_PROTOTYPES - Success
  -- Performing Test HAVE_CXX_WSTRICT_PROTOTYPES
  -- Performing Test HAVE_CXX_WSTRICT_PROTOTYPES - Failed
  -- Performing Test HAVE_C_WSTRICT_PROTOTYPES
  -- Performing Test HAVE_C_WSTRICT_PROTOTYPES - Success
  -- Performing Test HAVE_CXX_WUNDEF
  -- Performing Test HAVE_CXX_WUNDEF - Success
  -- Performing Test HAVE_C_WUNDEF
  -- Performing Test HAVE_C_WUNDEF - Success
  -- Performing Test HAVE_CXX_WINIT_SELF
  -- Performing Test HAVE_CXX_WINIT_SELF - Success
  -- Performing Test HAVE_C_WINIT_SELF
  -- Performing Test HAVE_C_WINIT_SELF - Success
  -- Performing Test HAVE_CXX_WPOINTER_ARITH
  -- Performing Test HAVE_CXX_WPOINTER_ARITH - Success
  -- Performing Test HAVE_C_WPOINTER_ARITH
  -- Performing Test HAVE_C_WPOINTER_ARITH - Success
  -- Performing Test HAVE_CXX_WSHADOW
  -- Performing Test HAVE_CXX_WSHADOW - Success
  -- Performing Test HAVE_C_WSHADOW
  -- Performing Test HAVE_C_WSHADOW - Success
  -- Performing Test HAVE_CXX_WSIGN_PROMO
  -- Performing Test HAVE_CXX_WSIGN_PROMO - Success
  -- Performing Test HAVE_C_WSIGN_PROMO
  -- Performing Test HAVE_C_WSIGN_PROMO - Failed
  -- Performing Test HAVE_CXX_WUNINITIALIZED
  -- Performing Test HAVE_CXX_WUNINITIALIZED - Success
  -- Performing Test HAVE_C_WUNINITIALIZED
  -- Performing Test HAVE_C_WUNINITIALIZED - Success
  -- Performing Test HAVE_CXX_WSUGGEST_OVERRIDE
  -- Performing Test HAVE_CXX_WSUGGEST_OVERRIDE - Success
  -- Performing Test HAVE_C_WSUGGEST_OVERRIDE
  -- Performing Test HAVE_C_WSUGGEST_OVERRIDE - Failed
  -- Performing Test HAVE_CXX_WNO_DELETE_NON_VIRTUAL_DTOR
  -- Performing Test HAVE_CXX_WNO_DELETE_NON_VIRTUAL_DTOR - Success
  -- Performing Test HAVE_C_WNO_DELETE_NON_VIRTUAL_DTOR
  -- Performing Test HAVE_C_WNO_DELETE_NON_VIRTUAL_DTOR - Failed
  -- Performing Test HAVE_CXX_WNO_UNNAMED_TYPE_TEMPLATE_ARGS
  -- Performing Test HAVE_CXX_WNO_UNNAMED_TYPE_TEMPLATE_ARGS - Failed
  -- Performing Test HAVE_C_WNO_UNNAMED_TYPE_TEMPLATE_ARGS
  -- Performing Test HAVE_C_WNO_UNNAMED_TYPE_TEMPLATE_ARGS - Failed
  -- Performing Test HAVE_CXX_WNO_COMMENT
  -- Performing Test HAVE_CXX_WNO_COMMENT - Success
  -- Performing Test HAVE_C_WNO_COMMENT
  -- Performing Test HAVE_C_WNO_COMMENT - Success
  -- Performing Test HAVE_CXX_WIMPLICIT_FALLTHROUGH_3
  -- Performing Test HAVE_CXX_WIMPLICIT_FALLTHROUGH_3 - Success
  -- Performing Test HAVE_C_WIMPLICIT_FALLTHROUGH_3
  -- Performing Test HAVE_C_WIMPLICIT_FALLTHROUGH_3 - Success
  -- Performing Test HAVE_CXX_WNO_STRICT_OVERFLOW
  -- Performing Test HAVE_CXX_WNO_STRICT_OVERFLOW - Success
  -- Performing Test HAVE_C_WNO_STRICT_OVERFLOW
  -- Performing Test HAVE_C_WNO_STRICT_OVERFLOW - Success
  -- Performing Test HAVE_CXX_FDIAGNOSTICS_SHOW_OPTION
  -- Performing Test HAVE_CXX_FDIAGNOSTICS_SHOW_OPTION - Success
  -- Performing Test HAVE_C_FDIAGNOSTICS_SHOW_OPTION
  -- Performing Test HAVE_C_FDIAGNOSTICS_SHOW_OPTION - Success
  -- Performing Test HAVE_CXX_PTHREAD
  -- Performing Test HAVE_CXX_PTHREAD - Success
  -- Performing Test HAVE_C_PTHREAD
  -- Performing Test HAVE_C_PTHREAD - Success
  -- Performing Test HAVE_CXX_FOMIT_FRAME_POINTER
  -- Performing Test HAVE_CXX_FOMIT_FRAME_POINTER - Success
  -- Performing Test HAVE_C_FOMIT_FRAME_POINTER
  -- Performing Test HAVE_C_FOMIT_FRAME_POINTER - Success
  -- Performing Test HAVE_CXX_FFUNCTION_SECTIONS
  -- Performing Test HAVE_CXX_FFUNCTION_SECTIONS - Success
  -- Performing Test HAVE_C_FFUNCTION_SECTIONS
  -- Performing Test HAVE_C_FFUNCTION_SECTIONS - Success
  -- Performing Test HAVE_CXX_FDATA_SECTIONS
  -- Performing Test HAVE_CXX_FDATA_SECTIONS - Success
  -- Performing Test HAVE_C_FDATA_SECTIONS
  -- Performing Test HAVE_C_FDATA_SECTIONS - Success
  -- Performing Test HAVE_CXX_MFPU_VFPV3
  -- Performing Test HAVE_CXX_MFPU_VFPV3 - Success
  -- Performing Test HAVE_CPU_NEON_SUPPORT (check file: cmake/checks/cpu_neon.cpp)
  -- Performing Test HAVE_CPU_NEON_SUPPORT - Failed
  -- Performing Test HAVE_CXX_MFPU_NEON (check file: cmake/checks/cpu_neon.cpp)
  -- Performing Test HAVE_CXX_MFPU_NEON - Success
  -- Performing Test HAVE_CPU_FP16_SUPPORT (check file: cmake/checks/cpu_fp16.cpp)
  -- Performing Test HAVE_CPU_FP16_SUPPORT - Failed
  -- Performing Test HAVE_CXX_MFPU_NEON_FP16_MFP16_FORMAT_IEEE (check file: cmake/checks/cpu_fp16.cpp)
  -- Performing Test HAVE_CXX_MFPU_NEON_FP16_MFP16_FORMAT_IEEE - Success
  -- Performing Test HAVE_CPU_BASELINE_FLAGS
  -- Performing Test HAVE_CPU_BASELINE_FLAGS - Success
  -- Performing Test HAVE_CXX_FVISIBILITY_HIDDEN
  -- Performing Test HAVE_CXX_FVISIBILITY_HIDDEN - Success
  -- Performing Test HAVE_C_FVISIBILITY_HIDDEN
  -- Performing Test HAVE_C_FVISIBILITY_HIDDEN - Success
  -- Performing Test HAVE_CXX_FVISIBILITY_INLINES_HIDDEN
  -- Performing Test HAVE_CXX_FVISIBILITY_INLINES_HIDDEN - Success
  -- Performing Test HAVE_C_FVISIBILITY_INLINES_HIDDEN
  -- Performing Test HAVE_C_FVISIBILITY_INLINES_HIDDEN - Failed
  -- Performing Test HAVE_LINK_AS_NEEDED
  -- Performing Test HAVE_LINK_AS_NEEDED - Success
  -- Looking for pthread.h
  -- Looking for pthread.h - found
  -- Looking for posix_memalign
  -- Looking for posix_memalign - found
  -- Looking for malloc.h
  -- Looking for malloc.h - found
  -- Looking for memalign
  -- Looking for memalign - found
  -- Found ZLIB: /usr/lib/arm-linux-gnueabihf/libz.so (found suitable version "1.2.11", minimum required is "1.2.3")
  -- Found JPEG: /usr/lib/arm-linux-gnueabihf/libjpeg.so (found version "62")
  -- Found TIFF: /usr/lib/arm-linux-gnueabihf/libtiff.so (found version "4.1.0")
  -- Performing Test HAVE_C_STD_C99
  -- Performing Test HAVE_C_STD_C99 - Success
  -- Performing Test HAVE_C_WNO_UNUSED_VARIABLE
  -- Performing Test HAVE_C_WNO_UNUSED_VARIABLE - Success
  -- Performing Test HAVE_C_WNO_UNUSED_FUNCTION
  -- Performing Test HAVE_C_WNO_UNUSED_FUNCTION - Success
  -- Performing Test HAVE_C_WNO_SHADOW
  -- Performing Test HAVE_C_WNO_SHADOW - Success
  -- Performing Test HAVE_C_WNO_MAYBE_UNINITIALIZED
  -- Performing Test HAVE_C_WNO_MAYBE_UNINITIALIZED - Success
  -- Performing Test HAVE_C_WNO_MISSING_PROTOTYPES
  -- Performing Test HAVE_C_WNO_MISSING_PROTOTYPES - Success
  -- Performing Test HAVE_C_WNO_MISSING_DECLARATIONS
  -- Performing Test HAVE_C_WNO_MISSING_DECLARATIONS - Success
  -- Performing Test HAVE_C_WNO_IMPLICIT_FALLTHROUGH
  -- Performing Test HAVE_C_WNO_IMPLICIT_FALLTHROUGH - Success
  -- Could NOT find OpenJPEG (minimal suitable version: 2.0, recommended version >= 2.3.1). OpenJPEG will be built from sources
  -- Performing Test HAVE_C_WNO_IMPLICIT_CONST_INT_FLOAT_CONVERSION
  -- Performing Test HAVE_C_WNO_IMPLICIT_CONST_INT_FLOAT_CONVERSION - Failed
  -- OpenJPEG: VERSION = 2.4.0, BUILD = opencv-4.5.5-openjp2-2.4.0
  -- Looking for string.h
  -- Looking for string.h - found
  -- Looking for memory.h
  -- Looking for memory.h - found
  -- Looking for stdlib.h
  -- Looking for stdlib.h - found
  -- Looking for stdio.h
  -- Looking for stdio.h - found
  -- Looking for math.h
  -- Looking for math.h - found
  -- Looking for float.h
  -- Looking for float.h - found
  -- Looking for time.h
  -- Looking for time.h - found
  -- Looking for stdarg.h
  -- Looking for stdarg.h - found
  -- Looking for ctype.h
  -- Looking for ctype.h - found
  -- Looking for assert.h
  -- Looking for assert.h - found
  -- Looking for stdint.h
  -- Looking for stdint.h - found
  -- Looking for inttypes.h
  -- Looking for inttypes.h - found
  -- Looking for strings.h
  -- Looking for strings.h - found
  -- Looking for sys/stat.h
  -- Looking for sys/stat.h - found
  -- Looking for sys/types.h
  -- Looking for sys/types.h - found
  -- Looking for unistd.h
  -- Looking for unistd.h - found
  -- Looking for include file malloc.h
  -- Looking for include file malloc.h - found
  -- Looking for _aligned_malloc
  -- Looking for _aligned_malloc - not found
  -- Looking for posix_memalign
  -- Looking for posix_memalign - found
  -- Looking for memalign
  -- Looking for memalign - found
  -- Performing Test HAVE_C_WNO_UNDEF
  -- Performing Test HAVE_C_WNO_UNDEF - Success
  -- Performing Test HAVE_C_WNO_STRICT_PROTOTYPES
  -- Performing Test HAVE_C_WNO_STRICT_PROTOTYPES - Success
  -- Performing Test HAVE_C_WNO_CAST_FUNCTION_TYPE
  -- Performing Test HAVE_C_WNO_CAST_FUNCTION_TYPE - Success
  -- OpenJPEG libraries will be built from sources: libopenjp2 (version "2.4.0")
  -- Found ZLIB: /usr/lib/arm-linux-gnueabihf/libz.so (found version "1.2.11")
  -- Found PNG: /usr/lib/arm-linux-gnueabihf/libpng.so (found version "1.6.36")
  -- Looking for /usr/include/libpng/png.h
  -- Looking for /usr/include/libpng/png.h - found
  -- Looking for semaphore.h
  -- Looking for semaphore.h - found
  -- Performing Test HAVE_CXX_WNO_SHADOW
  -- Performing Test HAVE_CXX_WNO_SHADOW - Success
  -- Performing Test HAVE_CXX_WNO_UNUSED
  -- Performing Test HAVE_CXX_WNO_UNUSED - Success
  -- Performing Test HAVE_CXX_WNO_SIGN_COMPARE
  -- Performing Test HAVE_CXX_WNO_SIGN_COMPARE - Success
  -- Performing Test HAVE_CXX_WNO_UNDEF
  -- Performing Test HAVE_CXX_WNO_UNDEF - Success
  -- Performing Test HAVE_CXX_WNO_MISSING_DECLARATIONS
  -- Performing Test HAVE_CXX_WNO_MISSING_DECLARATIONS - Success
  -- Performing Test HAVE_CXX_WNO_UNINITIALIZED
  -- Performing Test HAVE_CXX_WNO_UNINITIALIZED - Success
  -- Performing Test HAVE_CXX_WNO_SWITCH
  -- Performing Test HAVE_CXX_WNO_SWITCH - Success
  -- Performing Test HAVE_CXX_WNO_PARENTHESES
  -- Performing Test HAVE_CXX_WNO_PARENTHESES - Success
  -- Performing Test HAVE_CXX_WNO_ARRAY_BOUNDS
  -- Performing Test HAVE_CXX_WNO_ARRAY_BOUNDS - Success
  -- Performing Test HAVE_CXX_WNO_EXTRA
  -- Performing Test HAVE_CXX_WNO_EXTRA - Success
  -- Performing Test HAVE_CXX_WNO_DEPRECATED_DECLARATIONS
  -- Performing Test HAVE_CXX_WNO_DEPRECATED_DECLARATIONS - Success
  -- Performing Test HAVE_CXX_WNO_MISLEADING_INDENTATION
  -- Performing Test HAVE_CXX_WNO_MISLEADING_INDENTATION - Success
  -- Performing Test HAVE_CXX_WNO_DEPRECATED
  -- Performing Test HAVE_CXX_WNO_DEPRECATED - Success
  -- Performing Test HAVE_CXX_WNO_SUGGEST_OVERRIDE
  -- Performing Test HAVE_CXX_WNO_SUGGEST_OVERRIDE - Success
  -- Performing Test HAVE_CXX_WNO_INCONSISTENT_MISSING_OVERRIDE
  -- Performing Test HAVE_CXX_WNO_INCONSISTENT_MISSING_OVERRIDE - Failed
  -- Performing Test HAVE_CXX_WNO_IMPLICIT_FALLTHROUGH
  -- Performing Test HAVE_CXX_WNO_IMPLICIT_FALLTHROUGH - Success
  -- Performing Test HAVE_CXX_WNO_TAUTOLOGICAL_COMPARE
  -- Performing Test HAVE_CXX_WNO_TAUTOLOGICAL_COMPARE - Success
  -- Performing Test HAVE_CXX_WNO_MISSING_PROTOTYPES
  -- Performing Test HAVE_CXX_WNO_MISSING_PROTOTYPES - Failed
  -- Performing Test HAVE_CXX_WNO_REORDER
  -- Performing Test HAVE_CXX_WNO_REORDER - Success
  -- Performing Test HAVE_CXX_WNO_UNUSED_RESULT
  -- Performing Test HAVE_CXX_WNO_UNUSED_RESULT - Success
  -- Performing Test HAVE_CXX_WNO_IMPLICIT_CONST_INT_FLOAT_CONVERSION
  -- Performing Test HAVE_CXX_WNO_IMPLICIT_CONST_INT_FLOAT_CONVERSION - Failed
  -- Performing Test HAVE_CXX_WNO_CLASS_MEMACCESS
  -- Performing Test HAVE_CXX_WNO_CLASS_MEMACCESS - Success
  -- Could not find OpenBLAS include. Turning OpenBLAS_FOUND off
  -- Could not find OpenBLAS lib. Turning OpenBLAS_FOUND off
  -- Could NOT find Atlas (missing: Atlas_CLAPACK_INCLUDE_DIR)
  -- Looking for sgemm_
  -- Looking for sgemm_ - not found
  -- Found Threads: TRUE
  -- Looking for dgemm_
  -- Looking for dgemm_ - found
  -- Found BLAS: /usr/lib/arm-linux-gnueabihf/libblas.so;/usr/lib/arm-linux-gnueabihf/libf77blas.so;/usr/lib/arm-linux-gnueabihf/libatlas.so
  -- Looking for cheev_
  -- Looking for cheev_ - not found
  -- Looking for cheev_
  -- Looking for cheev_ - not found
  -- Looking for cheev_
  -- Looking for cheev_ - found
  -- Found LAPACK: /usr/lib/arm-linux-gnueabihf/liblapack.so;/usr/lib/arm-linux-gnueabihf/libblas.so;/usr/lib/arm-linux-gnueabihf/libf77blas.so;/usr/lib/arm-linux-gnueabihf/libatlas.so
  -- Performing Test HAVE_CXX_WNO_UNUSED_PARAMETER
  -- Performing Test HAVE_CXX_WNO_UNUSED_PARAMETER - Success
  -- Performing Test HAVE_CXX_WNO_UNUSED_LOCAL_TYPEDEFS
  -- Performing Test HAVE_CXX_WNO_UNUSED_LOCAL_TYPEDEFS - Success
  -- Performing Test HAVE_CXX_WNO_SIGN_PROMO
  -- Performing Test HAVE_CXX_WNO_SIGN_PROMO - Success
  -- Performing Test HAVE_CXX_WNO_TAUTOLOGICAL_UNDEFINED_COMPARE
  -- Performing Test HAVE_CXX_WNO_TAUTOLOGICAL_UNDEFINED_COMPARE - Failed
  -- Performing Test HAVE_CXX_WNO_IGNORED_QUALIFIERS
  -- Performing Test HAVE_CXX_WNO_IGNORED_QUALIFIERS - Success
  -- Performing Test HAVE_CXX_WNO_UNUSED_FUNCTION
  -- Performing Test HAVE_CXX_WNO_UNUSED_FUNCTION - Success
  -- Performing Test HAVE_CXX_WNO_UNUSED_CONST_VARIABLE
  -- Performing Test HAVE_CXX_WNO_UNUSED_CONST_VARIABLE - Success
  -- Performing Test HAVE_CXX_WNO_SHORTEN_64_TO_32
  -- Performing Test HAVE_CXX_WNO_SHORTEN_64_TO_32 - Failed
  -- Performing Test HAVE_CXX_WNO_INVALID_OFFSETOF
  -- Performing Test HAVE_CXX_WNO_INVALID_OFFSETOF - Success
  -- Performing Test HAVE_CXX_WNO_ENUM_COMPARE_SWITCH
  -- Performing Test HAVE_CXX_WNO_ENUM_COMPARE_SWITCH - Failed
  /bin/ant: 1: cd: can't cd to /bin/../share/ant/bin/..
  Error: Could not find or load main class org.apache.tools.ant.launch.Launcher
  Caused by: java.lang.ClassNotFoundException: org.apache.tools.ant.launch.Launcher
  -- Could NOT find JNI (missing: JAVA_AWT_LIBRARY JAVA_JVM_LIBRARY JAVA_INCLUDE_PATH JAVA_INCLUDE_PATH2 JAVA_AWT_INCLUDE_PATH)
  -- VTK is not found. Please set -DVTK_DIR in CMake to VTK build directory, or to VTK install subdirectory with VTKConfig.cmake file
  -- Carotene: NEON is not available, disabling carotene...
  -- Looking for dlerror in dl
  -- Looking for dlerror in dl - found
  -- Performing Test HAVE_C_WNO_SIGN_COMPARE
  -- Performing Test HAVE_C_WNO_SIGN_COMPARE - Success
  -- ADE: Download: v0.1.1f.zip
  -- Checking for module 'gtk+-3.0'
  --   Found gtk+-3.0, version 3.24.5
  -- Checking for module 'gtk+-2.0'
  --   Found gtk+-2.0, version 2.24.32
  -- Checking for module 'gthread-2.0'
  --   Found gthread-2.0, version 2.58.3
  -- Checking for modules 'libavcodec;libavformat;libavutil;libswscale'
  --   Found libavcodec, version 58.35.100
  --   Found libavformat, version 58.20.100
  --   Found libavutil, version 56.22.100
  --   Found libswscale, version 5.3.100
  -- Checking for module 'libavresample'
  --   Found libavresample, version 4.0.0
  -- Checking for module 'gstreamer-base-1.0'
  --   No package 'gstreamer-base-1.0' found
  -- Checking for module 'gstreamer-app-1.0'
  --   No package 'gstreamer-app-1.0' found
  -- Checking for module 'gstreamer-riff-1.0'
  --   No package 'gstreamer-riff-1.0' found
  -- Checking for module 'gstreamer-pbutils-1.0'
  --   No package 'gstreamer-pbutils-1.0' found
  -- Checking for module 'gstreamer-video-1.0'
  --   No package 'gstreamer-video-1.0' found
  -- Checking for module 'gstreamer-audio-1.0'
  --   No package 'gstreamer-audio-1.0' found
  -- Checking for module 'libdc1394-2'
  --   Found libdc1394-2, version 2.2.5
  -- Module opencv_alphamat disabled because the following dependencies are not found: Eigen
  -- Checking for module 'freetype2'
  --   Found freetype2, version 22.1.16
  -- Checking for module 'harfbuzz'
  --   Found harfbuzz, version 2.3.1
  -- freetype2:   YES (ver 22.1.16)
  -- harfbuzz:    YES (ver 2.3.1)
  -- Found HDF5: /usr/lib/arm-linux-gnueabihf/hdf5/serial/libhdf5.so;/usr/lib/arm-linux-gnueabihf/libpthread.so;/usr/lib/arm-linux-gnueabihf/libsz.so;/usr/lib/arm-linux-gnueabihf/libz.so;/usr/lib/arm-linux-gnueabihf/libdl.so;/usr/lib/arm-linux-gnueabihf/libm.so (found version "1.10.4")
  -- Julia not found. Not compiling Julia Bindings.
  -- Module opencv_ovis disabled because OGRE3D was not found
  -- No preference for use of exported gflags CMake configuration set, and no hints for include/library directories provided. Defaulting to preferring an installed/exported gflags CMake configuration if available.
  -- Failed to find installed gflags CMake configuration, searching for gflags build directories exported with CMake.
  -- Failed to find gflags - Failed to find an installed/exported CMake configuration for gflags, will perform search for installed gflags components.
  -- Failed to find gflags - Could not find gflags include directory, set GFLAGS_INCLUDE_DIR to directory containing gflags/gflags.h
  -- Failed to find glog - Could not find glog include directory, set GLOG_INCLUDE_DIR to directory containing glog/logging.h
  -- Module opencv_sfm disabled because the following dependencies are not found: Eigen Glog/Gflags
  -- Checking for module 'tesseract'
  --   No package 'tesseract' found
  -- Tesseract:   NO
  -- Allocator metrics storage type: 'int'
  -- Excluding from source files list: modules/imgproc/src/corner.avx.cpp
  -- Excluding from source files list: modules/imgproc/src/imgwarp.avx2.cpp
  -- Excluding from source files list: modules/imgproc/src/imgwarp.sse4_1.cpp
  -- Excluding from source files list: modules/imgproc/src/resize.avx2.cpp
  -- Excluding from source files list: modules/imgproc/src/resize.sse4_1.cpp
  -- Registering hook 'INIT_MODULE_SOURCES_opencv_dnn': /tmp/pip-install-lvel8qyn/opencv-contrib-python_eafbac0653b8480faaa76d62d11bdf93/opencv/modules/dnn/cmake/hooks/INIT_MODULE_SOURCES_opencv_dnn.cmake
  -- opencv_dnn: filter out cuda4dnn source code
  -- Excluding from source files list: <BUILD>/modules/dnn/layers/layers_common.avx.cpp
  -- Excluding from source files list: <BUILD>/modules/dnn/layers/layers_common.avx2.cpp
  -- Excluding from source files list: <BUILD>/modules/dnn/layers/layers_common.avx512_skx.cpp
  -- Excluding from source files list: <BUILD>/modules/dnn/layers/layers_common.rvv.cpp
  -- Excluding from source files list: <BUILD>/modules/dnn/int8layers/layers_common.avx2.cpp
  -- Excluding from source files list: <BUILD>/modules/dnn/int8layers/layers_common.avx512_skx.cpp
  -- Excluding from source files list: modules/features2d/src/fast.avx2.cpp
  -- imgcodecs: OpenEXR codec is disabled in runtime. Details: https://github.com/opencv/opencv/issues/21326
  -- Performing Test HAVE_CXX_WNO_OVERLOADED_VIRTUAL
  -- Performing Test HAVE_CXX_WNO_OVERLOADED_VIRTUAL - Success
  -- Performing Test Iconv_IS_BUILT_IN
  -- Performing Test Iconv_IS_BUILT_IN - Success
  -- wechat_qrcode: Download: detect.caffemodel
  -- wechat_qrcode: Download: detect.prototxt
  -- wechat_qrcode: Download: sr.caffemodel
  -- wechat_qrcode: Download: sr.prototxt
  -- highgui: using builtin backend: GTK3
  -- rgbd: Eigen support is disabled. Eigen is Required for Posegraph optimization
  -- xfeatures2d/boostdesc: Download: boostdesc_bgm.i
  -- xfeatures2d/boostdesc: Download: boostdesc_bgm_bi.i
  -- xfeatures2d/boostdesc: Download: boostdesc_bgm_hd.i
  -- xfeatures2d/boostdesc: Download: boostdesc_binboost_064.i
  -- xfeatures2d/boostdesc: Download: boostdesc_binboost_128.i
  -- xfeatures2d/boostdesc: Download: boostdesc_binboost_256.i
  -- xfeatures2d/boostdesc: Download: boostdesc_lbgm.i
  -- xfeatures2d/vgg: Download: vgg_generated_48.i
  -- xfeatures2d/vgg: Download: vgg_generated_64.i
  -- xfeatures2d/vgg: Download: vgg_generated_80.i
  -- xfeatures2d/vgg: Download: vgg_generated_120.i
  -- data: Download: face_landmark_model.dat
  -- Found 'misc' Python modules from /tmp/pip-install-lvel8qyn/opencv-contrib-python_eafbac0653b8480faaa76d62d11bdf93/opencv/modules/python/package/extra_modules
  -- Found 'mat_wrapper;utils' Python modules from /tmp/pip-install-lvel8qyn/opencv-contrib-python_eafbac0653b8480faaa76d62d11bdf93/opencv/modules/core/misc/python/package
  -- Found 'gapi' Python modules from /tmp/pip-install-lvel8qyn/opencv-contrib-python_eafbac0653b8480faaa76d62d11bdf93/opencv/modules/gapi/misc/python/package
  -- Performing Test HAVE_CXX_WNO_UNUSED_PRIVATE_FIELD
  -- Performing Test HAVE_CXX_WNO_UNUSED_PRIVATE_FIELD - Failed
  -- Found 'misc' Python modules from /tmp/pip-install-lvel8qyn/opencv-contrib-python_eafbac0653b8480faaa76d62d11bdf93/opencv/modules/python/package/extra_modules
  -- Found 'mat_wrapper;utils' Python modules from /tmp/pip-install-lvel8qyn/opencv-contrib-python_eafbac0653b8480faaa76d62d11bdf93/opencv/modules/core/misc/python/package
  -- Found 'gapi' Python modules from /tmp/pip-install-lvel8qyn/opencv-contrib-python_eafbac0653b8480faaa76d62d11bdf93/opencv/modules/gapi/misc/python/package
  --
  -- General configuration for OpenCV 4.5.5 =====================================
  --   Version control:               unknown
  --
  --   Extra modules:
  --     Location (extra):            /tmp/pip-install-lvel8qyn/opencv-contrib-python_eafbac0653b8480faaa76d62d11bdf93/opencv_contrib/modules
  --     Version control (extra):     unknown
  --
  --   Platform:
  --     Timestamp:                   2022-01-16T03:25:44Z
  --     Host:                        Linux 5.10.63-v7l+ armv7l
  --     CMake:                       3.22.1
  --     CMake generator:             Ninja
  --     CMake build tool:            /usr/bin/ninja
  --     Configuration:               Release
  --
  --   CPU/HW features:
  --     Baseline:
  --       requested:                 DETECT
  --
  --   C/C++:
  --     Built as dynamic libs?:      NO
  --     C++ standard:                11
  --     C++ Compiler:                /usr/bin/c++  (ver 8.3.0)
  --     C++ flags (Release):         -fsigned-char -W -Wall -Werror=return-type -Werror=non-virtual-dtor -Werror=address -Werror=sequence-point -Wformat -Werror=format-security -Wmissing-declarations -Wundef -Winit-self -Wpointer-arith -Wshadow -Wsign-promo -Wuninitialized -Wsuggest-override -Wno-delete-non-virtual-dtor -Wno-comment -Wimplicit-fallthrough=3 -Wno-strict-overflow -fdiagnostics-show-option -pthread -fomit-frame-pointer -ffunction-sections -fdata-sections  -fvisibility=hidden -fvisibility-inlines-hidden -O3 -DNDEBUG  -DNDEBUG
  --     C++ flags (Debug):           -fsigned-char -W -Wall -Werror=return-type -Werror=non-virtual-dtor -Werror=address -Werror=sequence-point -Wformat -Werror=format-security -Wmissing-declarations -Wundef -Winit-self -Wpointer-arith -Wshadow -Wsign-promo -Wuninitialized -Wsuggest-override -Wno-delete-non-virtual-dtor -Wno-comment -Wimplicit-fallthrough=3 -Wno-strict-overflow -fdiagnostics-show-option -pthread -fomit-frame-pointer -ffunction-sections -fdata-sections  -fvisibility=hidden -fvisibility-inlines-hidden -g  -O0 -DDEBUG -D_DEBUG
  --     C Compiler:                  /usr/bin/cc
  --     C flags (Release):           -fsigned-char -W -Wall -Werror=return-type -Werror=non-virtual-dtor -Werror=address -Werror=sequence-point -Wformat -Werror=format-security -Wmissing-declarations -Wmissing-prototypes -Wstrict-prototypes -Wundef -Winit-self -Wpointer-arith -Wshadow -Wuninitialized -Wno-comment -Wimplicit-fallthrough=3 -Wno-strict-overflow -fdiagnostics-show-option -pthread -fomit-frame-pointer -ffunction-sections -fdata-sections  -fvisibility=hidden -O3 -DNDEBUG  -DNDEBUG
  --     C flags (Debug):             -fsigned-char -W -Wall -Werror=return-type -Werror=non-virtual-dtor -Werror=address -Werror=sequence-point -Wformat -Werror=format-security -Wmissing-declarations -Wmissing-prototypes -Wstrict-prototypes -Wundef -Winit-self -Wpointer-arith -Wshadow -Wuninitialized -Wno-comment -Wimplicit-fallthrough=3 -Wno-strict-overflow -fdiagnostics-show-option -pthread -fomit-frame-pointer -ffunction-sections -fdata-sections  -fvisibility=hidden -g  -O0 -DDEBUG -D_DEBUG
  --     Linker flags (Release):      -Wl,--gc-sections -Wl,--as-needed
  --     Linker flags (Debug):        -Wl,--gc-sections -Wl,--as-needed
  --     ccache:                      NO
  --     Precompiled headers:         NO
  --     Extra dependencies:          /usr/lib/arm-linux-gnueabihf/libjpeg.so /usr/lib/arm-linux-gnueabihf/libpng.so /usr/lib/arm-linux-gnueabihf/libtiff.so /usr/lib/arm-linux-gnueabihf/hdf5/serial/libhdf5.so /usr/lib/arm-linux-gnueabihf/libpthread.so /usr/lib/arm-linux-gnueabihf/libsz.so /usr/lib/arm-linux-gnueabihf/libz.so /usr/lib/arm-linux-gnueabihf/libdl.so /usr/lib/arm-linux-gnueabihf/libm.so Iconv::Iconv dl m pthread rt
  --     3rdparty dependencies:       libprotobuf ade ittnotify libwebp libopenjp2 IlmImf quirc
  --
  --   OpenCV modules:
  --     To be built:                 aruco barcode bgsegm bioinspired calib3d ccalib core datasets dnn dnn_objdetect dnn_superres dpm face features2d flann fuzzy gapi hdf hfs highgui img_hash imgcodecs imgproc intensity_transform line_descriptor mcc ml objdetect optflow phase_unwrapping photo plot python3 quality rapid reg rgbd saliency shape stereo stitching structured_light superres surface_matching text tracking video videoio videostab wechat_qrcode xfeatures2d ximgproc xobjdetect xphoto
  --     Disabled:                    freetype world
  --     Disabled by dependency:      -
  --     Unavailable:                 alphamat cudaarithm cudabgsegm cudacodec cudafeatures2d cudafilters cudaimgproc cudalegacy cudaobjdetect cudaoptflow cudastereo cudawarping cudev cvv java julia matlab ovis python2 sfm ts viz
  --     Applications:                -
  --     Documentation:               NO
  --     Non-free algorithms:         NO
  --
  --   GUI:                           GTK3
  --     GTK+:                        YES (ver 3.24.5)
  --       GThread :                  YES (ver 2.58.3)
  --       GtkGlExt:                  NO
  --     VTK support:                 NO
  --
  --   Media I/O:
  --     ZLib:                        /usr/lib/arm-linux-gnueabihf/libz.so (ver 1.2.11)
  --     JPEG:                        /usr/lib/arm-linux-gnueabihf/libjpeg.so (ver 62)
  --     WEBP:                        build (ver encoder: 0x020f)
  --     PNG:                         /usr/lib/arm-linux-gnueabihf/libpng.so (ver 1.6.36)
  --     TIFF:                        /usr/lib/arm-linux-gnueabihf/libtiff.so (ver 42 / 4.1.0)
  --     JPEG 2000:                   build (ver 2.4.0)
  --     OpenEXR:                     build (ver 2.3.0)
  --     HDR:                         YES
  --     SUNRASTER:                   YES
  --     PXM:                         YES
  --     PFM:                         YES
  --
  --   Video I/O:
  --     DC1394:                      YES (2.2.5)
  --     FFMPEG:                      YES
  --       avcodec:                   YES (58.35.100)
  --       avformat:                  YES (58.20.100)
  --       avutil:                    YES (56.22.100)
  --       swscale:                   YES (5.3.100)
  --       avresample:                YES (4.0.0)
  --     GStreamer:                   NO
  --     v4l/v4l2:                    YES (linux/videodev2.h)
  --
  --   Parallel framework:            pthreads
  --
  --   Trace:                         YES (with Intel ITT)
  --
  --   Other third-party libraries:
  --     Lapack:                      NO
  --     Eigen:                       NO
  --     Custom HAL:                  NO
  --     Protobuf:                    build (3.19.1)
  --
  --   OpenCL:                        YES (no extra features)
  --     Include path:                /tmp/pip-install-lvel8qyn/opencv-contrib-python_eafbac0653b8480faaa76d62d11bdf93/opencv/3rdparty/include/opencl/1.2
  --     Link libraries:              Dynamic load
  --
  --   Python 3:
  --     Interpreter:                 /usr/bin/python3 (ver 3.7.3)
  --     Libraries:                   /usr/lib/arm-linux-gnueabihf/libpython3.7m.so (ver 3.7.3)
  --     numpy:                       /tmp/pip-build-env-qedhc6x9/overlay/lib/python3.7/site-packages/numpy/core/include (ver 1.14.5)
  --     install path:                python/cv2/python-3
  --
  --   Python (for build):            /usr/bin/python3
  --
  --   Java:
  --     ant:                         NO
  --     JNI:                         NO
  --     Java wrappers:               NO
  --     Java tests:                  NO
  --
  --   Install to:                    /tmp/pip-install-lvel8qyn/opencv-contrib-python_eafbac0653b8480faaa76d62d11bdf93/_skbuild/linux-armv7l-3.7/cmake-install
  -- -----------------------------------------------------------------
  --
  -- Configuring done
  -- Generating done

```

</details>

**Comment by alalek** [comment]
Upgrade `numpy` through pip

**Comment by pauljurczak** [comment]
My Numpy version was only one patch release behind: `numpy-1.21.4`. It was way above `1.14.5` required by `opencv-contrib-python`:
```
Requirement already satisfied: numpy>=1.14.5 in ./.local/lib/python3.7/site-packages (from opencv-contrib-python) (1.21.5)
```
I'm getting the same error after upgrading to `numpy-1.21.5`
```
  /usr/include/python3.7m/numpy/ndarrayobject.h:236:9: error: ‘PyTuple_GET_SIZE’ was not declared in this scope
       if (PyTuple_GET_SIZE(value) != 3) {
           ^~~~~~~~~~~~~~~~
```
I don't know why configuration shows an old version, though:
```
  --   Python 3:
  --     Interpreter:                 /usr/bin/python3 (ver 3.7.3)
  --     Libraries:                   /usr/lib/arm-linux-gnueabihf/libpython3.7m.so (ver 3.7.3)
  --     numpy:                       /tmp/pip-build-env-_fwz01pa/overlay/lib/python3.7/site-packages/numpy/core/include (ver 1.14.5)
```

**Comment by alalek** [comment]
It is numpy issue (https://github.com/numpy/numpy/pull/13725 or https://github.com/numpy/numpy/pull/20818 ). So you need to upgrade numpy.

Or drop this option: https://github.com/opencv/opencv-python/blob/62/setup.py#L162


---

> why configuration

Try to clean build directory.

**Comment by pauljurczak** [comment]
I tried in virtual environment (`virtualenv`) and it fails in the same manner. I cleared `/tmp`. Numpy 1.21.5 is installed, but OpenCV configuration still refers to ver 1.14.5:
```
(.ocvp) pi@raspberrypi:~/ocvp $ pip list
Package       Version
------------- -------
numpy         1.21.5
pip           21.3.1
pkg_resources 0.0.0
setuptools    40.8.0
(.ocvp) pi@raspberrypi:~/ocvp $ pip install opencv-contrib-python
....
  --   Python 3:
  --     Interpreter:                 /home/pi/ocvp/.ocvp/bin/python3 (ver 3.7.3)
  --     Libraries:                   /usr/lib/arm-linux-gnueabihf/libpython3.7m.so (ver 3.7.3)
  --     numpy:                       /tmp/pip-build-env-ix7d38r5/overlay/lib/python3.7/site-packages/numpy/core/include (ver 1.14.5)
```
How do I make it to use the version installed in venv?

**Comment by adamp87** [comment]
I ran into the same issue and I think I have a solution. In short you need to install `libatlas-base-dev` as `sudo apt-get install libatlas-base-dev`, which replaces `libcblas-dev`.

I think the wheel of opencv 4.5.5.62 fails because of the replacement of the libcblas. With pip opencv version 4.5.4.60 can be downloaded.

I was trying to install the newest opencv-python "4.5.5.62" with pip and it was failing with "FileNotFoundError: [Errno 2] No such file or directory: '_skbuild/linux-armv7l". When running pip install in verbose, I saw it was compiling and during CMake it had the following error:
```
  -- Found PythonInterp: /usr/bin/python3 (found suitable version "3.9.2", minimum required is "2.7")
  CMake Warning at cmake/OpenCVDetectPython.cmake:81 (message):
    CMake's 'find_host_package(PythonInterp 2.7)' found wrong Python version:

    PYTHON_EXECUTABLE=/usr/bin/python3

    PYTHON_VERSION_STRING=3.9.2

    Consider providing the 'PYTHON2_EXECUTABLE' variable via CMake command line
    or environment variables

  Call Stack (most recent call first):
    cmake/OpenCVDetectPython.cmake:271 (find_python)
    CMakeLists.txt:627 (include)


  -- Could NOT find Python2 (missing: Python2_EXECUTABLE Interpreter)
      Reason given by package:
          Interpreter: Wrong major version for the interpreter "/usr/bin/python"

  -- Found PythonInterp: /usr/bin/python3 (found suitable version "3.9.2", minimum required is "3.2")
  -- Found PythonLibs: /usr/lib/arm-linux-gnueabihf/libpython3.9.so (found suitable exact version "3.9.2")
  Traceback (most recent call last):
    File "/tmp/pip-build-env-re5ewut_/overlay/lib/python3.9/site-packages/numpy/core/__init__.py", line 22, in <module>
      from . import multiarray
    File "/tmp/pip-build-env-re5ewut_/overlay/lib/python3.9/site-packages/numpy/core/multiarray.py", line 12, in <module>
      from . import overrides
    File "/tmp/pip-build-env-re5ewut_/overlay/lib/python3.9/site-packages/numpy/core/overrides.py", line 7, in <module>
      from numpy.core._multiarray_umath import (
  ImportError: libcblas.so.3: cannot open shared object file: No such file or directory

  During handling of the above exception, another exception occurred:

  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-build-env-re5ewut_/overlay/lib/python3.9/site-packages/numpy/__init__.py", line 140, in <module>
      from . import core
    File "/tmp/pip-build-env-re5ewut_/overlay/lib/python3.9/site-packages/numpy/core/__init__.py", line 48, in <module>
      raise ImportError(msg)
  ImportError:

  IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

  Importing the numpy C-extensions failed. This error can happen for
  many reasons, often due to issues with your setup or how NumPy was
  installed.

  We have compiled some common reasons and troubleshooting tips at:

      https://numpy.org/devdocs/user/troubleshooting-importerror.html

  Please note and check the following:

    * The Python version is: Python3.9 from "/usr/bin/python3"
    * The NumPy version is: "1.19.3"

  and make sure that they are the versions you expect.
  Please carefully study the documentation linked above for further help.

  Original error was: libcblas.so.3: cannot open shared object file: No such file or directory

  -- Looking for ccache - not found

```
Therefore at the end CMake's config output sad Python3 is unavailable.

I installed `opencv-python==4.5.4.60`, which was not necessary to compile as it  downloaded a wheel file. But when I was importing cv2, I run again into:

```
Python 3.9.2 (default, Mar 12 2021, 04:06:34)
[GCC 10.2.1 20210110] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import cv2
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/pi/.local/lib/python3.9/site-packages/cv2/__init__.py", line 8, in <module>
    from .cv2 import *
ImportError: libcblas.so.3: cannot open shared object file: No such file or directory
```

Therefore I tried to install as mentioned libcblas, but sudo apt-get tells it was replaced, so installed libatlas-base-dev. Now opencv 4.5.4.60 loads and also opencv 4.5.5.62 compiles. Im still waiting until it finishes, but now CMake set python3 correctly.

Conclusion: I think the wheel fails because of the replacement of the libcblas library to libatlas-base-dev.

**Comment by tbertels** [comment]
> How do I make it to use the version installed in venv?

pip uninstall numpy
sudo apt-get remove python-numpy

**Comment by tbertels** [comment]
The real issue here is that you need to run
`sudo pip3 install --upgrade pip`
Then install opencv-python with
`pip3 install opencv-python`
See https://pypi.org/project/opencv-python/

**Comment by Ittiz** [comment]
> The real issue here is that you need to run `sudo pip3 install --upgrade pip` Then install opencv-python with `pip3 install opencv-python` See https://pypi.org/project/opencv-python/ opencv-python doesn't need to be built.

I had the same issue as [pauljurczak](https://github.com/pauljurczak) and this indeed was the problem.  My Pip version was 18.1 and opencv requires 19.3 or higher.

**Comment by asmorkalov** [comment]
There is no target "conta_estaciona" in OpenCV. It's something in your app.

**Comment by asmorkalov** [comment]
The issue is closed as original problem reported by the issue starter has been resolved.

**Comment by homm** [comment]
Still fails to install:

```
$ MAKEFLAGS="-j8" pip install -v --no-binary opencv-contrib-python-headless opencv-contrib-python-headless==4.6.0.66
Using pip 22.2.2 from .../lib/python3.7/site-packages/pip (python 3.7)
Collecting opencv-contrib-python-headless==4.6.0.66
  Using cached opencv-contrib-python-headless-4.6.0.66.tar.gz (149.9 MB)
  Running command pip subprocess to install build dependencies
  Ignoring numpy: markers 'python_version == "3.6" and platform_machine != "aarch64" and platform_machine != "arm64"' don't match your environment
  Ignoring numpy: markers 'python_version == "3.8" and platform_machine != "aarch64" and platform_machine != "arm64"' don't match your environment
  Ignoring numpy: markers 'python_version <= "3.9" and sys_platform == "linux" and platform_machine == "aarch64"' don't match your environment
  Ignoring numpy: markers 'python_version <= "3.9" and sys_platform == "darwin" and platform_machine == "arm64"' don't match your environment
  Ignoring numpy: markers 'python_version == "3.9" and platform_machine != "aarch64" and platform_machine != "arm64"' don't match your environment
  Ignoring numpy: markers 'python_version >= "3.10"' don't match your environment
  Collecting setuptools==59.2.0
    Using cached setuptools-59.2.0-py3-none-any.whl (952 kB)
  Collecting wheel==0.37.0
    Using cached wheel-0.37.0-py2.py3-none-any.whl (35 kB)
  Collecting cmake>=3.1
    Using cached cmake-3.24.1.1-py2.py3-none-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (23.3 MB)
  Collecting pip
    Using cached pip-22.2.2-py3-none-any.whl (2.0 MB)
  Collecting scikit-build>=0.13.2
    Using cached scikit_build-0.15.0-py2.py3-none-any.whl (77 kB)
  Collecting numpy==1.14.5
    Using cached numpy-1.14.5-cp37-cp37m-manylinux1_x86_64.whl (12.2 MB)
```

numpy==1.14.5 is installed during installation.
